### PR TITLE
[IMP] make command name more understandable;

### PR DESCRIPTION
**Pull request by legalsylvain**
Please review.

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1:

**Comment by bealdav** [comment]
:8ball:

**Comment by hparfr** [comment]
"marcel" is quite long for a shortcut name.
And is already used in context of Docker.

**Comment by legalsylvain** [comment]
What ?!?

It's a shame ! After all I did for this project ?!? I will fork this repository and continue for my part. 

Bye !

**Comment by bealdav** [comment]
:smile_cat:

lol

**Pull request closed without merging**
